import profile from "@/app/(tabs)/profile"

export const icons={
    home: require('../assets/icons/home.png'),
    news: require('../assets/icons/news.png'),
    links: require('../assets/icons/links.png'),
    profile: require('../assets/icons/profile.png'),
    notification: require('../assets/icons/notification.png'),
    whatsApp: require('../assets/icons/whatsApp.png'),
    youtube: require('../assets/icons/youTube.png'),
    instagram: require('../assets/icons/instaGram.png'),
    teligram: require('../assets/icons/teliGram.png'),
    userprofile: require('../assets/icons/userProfile.png'),
    userabout:require('../assets/icons/userAbout.png'),
    userbills:require('../assets/icons/userBills.png'),
    userfeedback:require('../assets/icons/userFeedback.png'),
    userhelp:require('../assets/icons/userHelp.png'),
    usertestmonial:require('../assets/icons/userTestmonial.png'),
    userreturn: require('../assets/icons/userReturn.png'),
    usermap: require('../assets/icons/userMap.png'),
    description: require('../assets/icons/description.png'),
    content: require('../assets/icons/content.png'),
    whatuget: require('../assets/icons/whatuget.png'),
    rightarrow:require('../assets/icons/rightarrow.png'),
    checkimage: require('../assets/icons/checkimage.png'),
    phoneimage: require('../assets/icons/phoneimage.png'),
    otpimage: require('../assets/icons/otpimage.png'),
    downimage: require('../assets/icons/downimage.png'),
    filtericon: require('../assets/icons/filtericon.png'),
    sorticon: require('../assets/icons/sorticon.png'),
    foldericon: require('../assets/icons/foldericon.png'),
    pdficon: require('../assets/icons/pdficon.png'),
    checkicon: require('../assets/icons/checkicon.png'),
    downicon: require('../assets/icons/downicon.png'),
    chooseplan:require('../assets/icons/chooseplan.png'),
    userDetails: require('../assets/icons/userDetails.png'),
    candidateprofile:require('../assets/icons/candidateprofile.png'),
    successicon: require('../assets/icons/successicon.png'),
    seniordetailschaticon: require('../assets/icons/seniordetailschaticon.png'),
    seniordetailsmeeticon: require('../assets/icons/seniordetailsmeeticon.png'),
    collegedeliveredicon: require('../assets/icons/collegedeliveredicon.png'),
    lockicon: require('../assets/icons/lockicon.png'),
    CaretDown: require('../assets/icons/CaretDown.png'),
    upload: require('../assets/icons/upload.png'),
    privacy: require('../assets/icons/privacy.png'),
    uploadedicon: require('../assets/icons/uploadedicon.png'),
    preferencelist: require('../assets/icons/preferencelist.png'),
}